build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
test-job1:
  stage: test
  script:
    - echo "This is test job 1"
test-job2:
  stage: test
  script:
    - echo "This is test job 2"