default: &default
  adapter: postgresql
  encoding: unicode
  collation: ja_JP.UTF-8
  template: template0
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "123456") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_USERNAME", "tms_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_USERNAME", "tms_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_USERNAME", "tms_production") %>
